
name = "DashReactFontAwesomeIconPicker"
uuid = "1b08a953-4be3-4667-9a23-709d09e28d5d"
authors = ["Jon Thompson <jjt@tutanota.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
